#############################################################################
# Makefile for building: squeeze
# Generated by qmake (2.01a) (Qt 4.3.0) on: Mon Oct 1 16:52:41 2007
# Project:  Makefile.qmake
# Template: app
# Command: /usr/bin/qmake-qt4 -unix CONFIG\ -=\ release CONFIG\ +=\ debug -o Makefile Makefile.qmake
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -ggdb -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ibuild -Ibuild
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/SqueezeWindow.cpp \
		src/ImagesView.cpp \
		src/ImagesModel.cpp \
		src/ImageLoader.cpp \
		src/ImageResizer.cpp build/moc_SqueezeWindow.cpp \
		build/moc_ImageLoader.cpp \
		build/moc_ImagesModel.cpp \
		build/moc_ImageResizer.cpp \
		build/moc_ImagesView.cpp \
		qrc_resources.cpp
OBJECTS       = build/main.o \
		build/SqueezeWindow.o \
		build/ImagesView.o \
		build/ImagesModel.o \
		build/ImageLoader.o \
		build/ImageResizer.o \
		build/moc_SqueezeWindow.o \
		build/moc_ImageLoader.o \
		build/moc_ImagesModel.o \
		build/moc_ImageResizer.o \
		build/moc_ImagesView.o \
		build/qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Makefile.qmake
QMAKE_TARGET  = squeeze
DESTDIR       = 
TARGET        = squeeze

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Makefile.qmake  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix CONFIG\ -=\ release CONFIG\ +=\ debug -o Makefile Makefile.qmake
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix CONFIG\ -=\ release CONFIG\ +=\ debug -o Makefile Makefile.qmake

dist: 
	@$(CHK_DIR_EXISTS) build/squeeze1.0.0 || $(MKDIR) build/squeeze1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/squeeze1.0.0/ && $(COPY_FILE) --parents src/SqueezeWindow.h src/ImageLoader.h src/ImagesModel.h src/ImageResizer.h src/ImagesView.h build/squeeze1.0.0/ && $(COPY_FILE) --parents qrc/resources.qrc build/squeeze1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/SqueezeWindow.cpp src/ImagesView.cpp src/ImagesModel.cpp src/ImageLoader.cpp src/ImageResizer.cpp build/squeeze1.0.0/ && (cd `dirname build/squeeze1.0.0` && $(TAR) squeeze1.0.0.tar squeeze1.0.0 && $(COMPRESS) squeeze1.0.0.tar) && $(MOVE) `dirname build/squeeze1.0.0`/squeeze1.0.0.tar.gz . && $(DEL_FILE) -r build/squeeze1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_SqueezeWindow.cpp build/moc_ImageLoader.cpp build/moc_ImagesModel.cpp build/moc_ImageResizer.cpp build/moc_ImagesView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_SqueezeWindow.cpp build/moc_ImageLoader.cpp build/moc_ImagesModel.cpp build/moc_ImageResizer.cpp build/moc_ImagesView.cpp
build/moc_SqueezeWindow.cpp: src/SqueezeWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/SqueezeWindow.h -o build/moc_SqueezeWindow.cpp

build/moc_ImageLoader.cpp: src/ImageLoader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ImageLoader.h -o build/moc_ImageLoader.cpp

build/moc_ImagesModel.cpp: src/ImageLoader.h \
		src/ImageResizer.h \
		src/ImagesModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ImagesModel.h -o build/moc_ImagesModel.cpp

build/moc_ImageResizer.cpp: src/ImageResizer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ImageResizer.h -o build/moc_ImageResizer.cpp

build/moc_ImagesView.cpp: src/ImagesView.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ImagesView.h -o build/moc_ImagesView.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: qrc/resources.qrc \
		qrc/fileopen.png \
		qrc/resize.png
	/usr/bin/rcc -name resources qrc/resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

build/main.o: src/main.cpp src/SqueezeWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/SqueezeWindow.o: src/SqueezeWindow.cpp src/ImagesModel.h \
		src/ImageLoader.h \
		src/ImageResizer.h \
		src/ImagesView.h \
		src/SqueezeWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SqueezeWindow.o src/SqueezeWindow.cpp

build/ImagesView.o: src/ImagesView.cpp src/ImagesView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ImagesView.o src/ImagesView.cpp

build/ImagesModel.o: src/ImagesModel.cpp src/SqueezeWindow.h \
		src/ImagesModel.h \
		src/ImageLoader.h \
		src/ImageResizer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ImagesModel.o src/ImagesModel.cpp

build/ImageLoader.o: src/ImageLoader.cpp src/ImageLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ImageLoader.o src/ImageLoader.cpp

build/ImageResizer.o: src/ImageResizer.cpp src/ImageResizer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ImageResizer.o src/ImageResizer.cpp

build/moc_SqueezeWindow.o: build/moc_SqueezeWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_SqueezeWindow.o build/moc_SqueezeWindow.cpp

build/moc_ImageLoader.o: build/moc_ImageLoader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ImageLoader.o build/moc_ImageLoader.cpp

build/moc_ImagesModel.o: build/moc_ImagesModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ImagesModel.o build/moc_ImagesModel.cpp

build/moc_ImageResizer.o: build/moc_ImageResizer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ImageResizer.o build/moc_ImageResizer.cpp

build/moc_ImagesView.o: build/moc_ImagesView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ImagesView.o build/moc_ImagesView.cpp

build/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

